DROP SCHEMA IF EXISTS SCHIV2;
CREATE SCHEMA SCHIV2 COLLATE utf8_bin;
USE SCHIV2;

CREATE TABLE FAKULTIES (
  FakultyID INT UNSIGNED PRIMARY KEY,
  Fakulty VARCHAR(255) NOT NULL
);

CREATE TABLE USERS (
  NutzerID INT UNSIGNED PRIMARY KEY,
  Vorname VARCHAR(255) NOT NULL,
  Nachname VARCHAR(255) NOT NULL,
  PasswordHash CHAR(64) NOT NULL,
  Status ENUM('student', 'dozent') NOT NULL DEFAULT 'student',
  Admin INT(1) NOT NULL DEFAULT 0,
  Gesperrt INT(1) NOT NULL DEFAULT 0,
  FakultyID INT UNSIGNED,

  FOREIGN KEY (FakultyID) REFERENCES FAKULTIES(FakultyID)
);

CREATE TABLE SPRECHSTUNDEN (
  SprechstundenID INT UNSIGNED PRIMARY KEY,
  DozentID INT UNSIGNED NOT NULL,
  Beschreibung VARCHAR(255) NOT NULL,
  UhrzeitVon DATE NOT NULL,
  UhrzeitBIS DATE NOT NULL,
  Einheiten INT UNSIGNED NOT NULL DEFAULT 0,
  autoConfirmation INT(1) NOT NULL DEFAULT 0,
  deleted INT(1) NOT NULL DEFAULT 0,

  FOREIGN KEY (DozentID) REFERENCES USERS(NutzerID)
);

CREATE TABLE EINSCHREIBUNGEN (
  StudentID INT UNSIGNED NOT NULL,
  SprechstundenID INT UNSIGNED NOT NULL,
  confirmed ENUM('ja', 'nein', 'ausstehend') NOT NULL DEFAULT 'ausstehend',
  Bermerkung TEXT NOT NULL,

  FOREIGN KEY (StudentID) REFERENCES USERS(NutzerID),
  FOREIGN KEY (SprechstundenID) REFERENCES SPRECHSTUNDEN(SprechstundenID)
);

CREATE TABLE BLOCKIERTE_STUDENTEN (
  DozentID INT UNSIGNED NOT NULL,
  StudentID INT UNSIGNED NOT NULL,
  Bemerkung VARCHAR(255) NOT NULL,

  FOREIGN KEY (DozentID) REFERENCES USERS(NutzerID),
  FOREIGN KEY (StudentID) REFERENCES USERS(NutzerID)
);

CREATE TABLE ROOT (
  PasswordHash CHAR(64) NOT NULL
);

CREATE TABLE BILDER (
  BildID INT UNSIGNED PRIMARY KEY,
  Bild BLOB NOT NULL
);