INSERT INTO SCHIV2_FACULTIES (FACULTY) VALUES ('Informatik');
INSERT INTO SCHIV2_FACULTIES (FACULTY) VALUES ('Wirtschaft');
INSERT INTO SCHIV2_FACULTIES (FACULTY) VALUES ('Ingenieur');


INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES (1, 'Dozent', 'doz', 'dozent', 'dozent', 1);

INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES (2, 'Audrey',    'Langdon', 'audrey.langdon@hof-university.de',   'dozent', 1);
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES (3, 'Caroline',  'Jackson', 'caroline.jackson@hof-university.de', 'dozent', 1);
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES (4, 'Melanie',   'Hart',    'melanie.hart@hof-university.de',     'dozent', 1);
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES (5, 'Christian', 'Kerr',    'christian.kerr@hof-university.de',   'dozent', 1);
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES (6, 'Lillian',   'Harris',  'lillian.harris@hof-university.de',   'dozent', 1);
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES (7, 'Alexandra', 'Watson',  'alexandra.watson@hof-university.de', 'dozent', 1);
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES (8, 'Sam',       'Watson',  'sam.watson@hof-university.de',       'dozent', 1);


INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES (9, 'Student', 'stud', 'student', 'student');

INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES (10, 'Mason',   'Ratchford',   'mason.ratchford@hof-university.de',    'student');
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES (11, 'Ted',     'Clarkson',    'ted.clarkson@hof-university.de',       'student');
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES (12, 'Levin',   'Yanosky',     'levin.yanosky@hof-university.de',      'student');
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES (13, 'Sharai',  'Schlesinger', 'sharai.schlesinger@hof-university.de', 'student');
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES (14, 'Falkner', 'Batinti',     'falkner.batinti@hof-university.de',    'student');
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES (15, 'Wilone',  'Viens',       'wilone.viens@hof-university.de',       'student');
INSERT INTO SCHIV2_USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES (16, 'Alano',   'Desjardins',  'alano.desjardins@hof-university.de',   'student');


INSERT INTO SCHIV2_MEETINGS (MEETINGID, DOZENTID, DESCRIPTION, TIMEFROM, TIMETO, UNITS, AUTOCONFIRMATION, DELETED) VALUES (1, 1, 'Sprechstunde', '01-APR-18 01.00.00.000000 PM', '01-APR-18 02.30.00.000000 PM', 6, 0, 0);
INSERT INTO SCHIV2_MEETINGS (MEETINGID, DOZENTID, DESCRIPTION, TIMEFROM, TIMETO, UNITS, AUTOCONFIRMATION, DELETED) VALUES (2, 1, 'Sprechstunde', '07-MAY-18 08.00.00.000000 AM', '07-MAY-18 10.00.00.000000 AM', 0, 0, 0);

INSERT INTO SCHIV2_MEETINGS (MEETINGID, DOZENTID, DESCRIPTION, TIMEFROM, TIMETO, UNITS, AUTOCONFIRMATION, DELETED) VALUES (3, 1, 'Sprechstunde', '01-AUG-18 01.00.00.000000 PM', '01-AUG-18 02.30.00.000000 PM', 6, 0, 0);
INSERT INTO SCHIV2_MEETINGS (MEETINGID, DOZENTID, DESCRIPTION, TIMEFROM, TIMETO, UNITS, AUTOCONFIRMATION, DELETED) VALUES (4, 1, 'Sprechstunde', '07-AUG-18 08.00.00.000000 AM', '07-AUG-18 10.00.00.000000 AM', 0, 0, 0);


INSERT INTO SCHIV2_INSCRIPTIONS (MEETINGID, STUDENTID, CONFIRMED, NOTE) VALUES (1, 9, 1, NULL);
INSERT INTO SCHIV2_INSCRIPTIONS (MEETINGID, STUDENTID, CONFIRMED, NOTE) VALUES (1, 15, -1, 'HaHa');

