INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES ('Dozent', 'doz', 'dozent', 'dozent', 1);

INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES ('Audrey',    'Langdon', 'audrey.langdon',   'dozent', 1);
INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES ('Caroline',  'Jackson', 'caroline.jackson', 'dozent', 1);
INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES ('Melanie',   'Hart',    'melanie.hart',     'dozent', 1);
INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES ('Christian', 'Kerr',    'christian.kerr',   'dozent', 1);
INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES ('Lillian',   'Harris',  'lillian.harris',   'dozent', 1);
INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES ('Alexandra', 'Watson',  'alexandra.watson', 'dozent', 1);
INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES ('Sam',       'Watson',  'sam.watson',       'dozent', 1);


INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES ('Student', 'stud', 'student', 'student');

INSERT INTO SCHIV2_ROOT (ID, PASSWORTHASH) VALUES (1, 'root');


