INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH, DOZENT) VALUES ('Dozent', 'doz', 'dozent', 'dozent', 1);

INSERT INTO SCHIV2_USERS (FIRSTNAME, LASTNAME, EMAIL, PASSWORDHASH) VALUES ('Student', 'stud', 'student', 'student');



